services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - workshop-net
    volumes:
      - ollama-local:/root/.ollama

  openWebUI:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    depends_on:
      - ollama
    ports:
      - 3000:8080
    networks:
      - workshop-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

networks:
  workshop-net:
    external: true

volumes:
  ollama-local:
  open-webui: